Fix `git tag` failing
Travis is failing with an error about the tag message not being
provided.

diff --git a/misc/travis-release.patch b/misc/travis-release.patch
--- a/misc/travis-release.patch
+++ b/misc/travis-release.patch
@@ -1,5 +1,5 @@
 --- release.sh.old	2019-12-06 18:19:57.890000000 -0500
-+++ release.sh.new	2019-12-06 18:33:42.803000000 -0500
++++ release.sh.new	2019-12-06 18:53:55.011000000 -0500
 @@ -1,5 +1,8 @@
  #!/bin/sh
  
@@ -9,7 +9,7 @@
  # TODO update versions and manpage timestamp
  # TODO check for changelog entry
  
-@@ -24,14 +27,6 @@
+@@ -24,23 +27,14 @@
  	die 'changes staged but not committed'
  fi
  
@@ -24,18 +24,19 @@
  echo 'Cleaning worktree'
  if ! git clean -dfX; then
  	die '`git clean -dfX` failed'
-@@ -42,6 +37,10 @@
- 	die '`git tag -s` failed'
  fi
  
+-echo 'Tagging'
+-if ! git tag -s v$VERSION; then
+-	die '`git tag -s` failed'
+-fi
 +# This needs to be here, *after* `git clean`, because reprotest sets ~ to the source directory
 +# so .gnupg ends up in the repository tree and gets removed by `git clean`.
 +gpg --import misc/test-keys.gpg
-+
+ 
  # We put these in a temporary directory so the first archive isn't included in the second, etc.
  echo 'Creating temporary directory'
- TMPDIR=$(mktemp -d)
-@@ -94,7 +93,4 @@
+@@ -94,7 +88,4 @@
  echo 'Cleaning up'
  rmdir $TMPDIR
  
