Fix reprotest filenames

diff --git a/misc/travis-release.patch b/misc/travis-release.patch
--- a/misc/travis-release.patch
+++ b/misc/travis-release.patch
@@ -1,5 +1,5 @@
---- release.sh.old	2019-12-06 17:02:09.896000000 -0500
-+++ release.sh.new	2019-12-06 17:18:20.140000000 -0500
+--- release.sh.old	2019-12-06 18:19:57.890000000 -0500
++++ release.sh.new	2019-12-06 18:33:42.803000000 -0500
 @@ -1,5 +1,8 @@
  #!/bin/sh
  
@@ -9,7 +9,7 @@
  # TODO update versions and manpage timestamp
  # TODO check for changelog entry
  
-@@ -24,10 +27,6 @@
+@@ -24,14 +27,6 @@
  	die 'changes staged but not committed'
  fi
  
@@ -17,10 +17,14 @@
 -	die 'unstaged changes present'
 -fi
 -
- if u="$(git ls-files --exclude-standard --others)" && ! test -z "$u"; then
- 	die 'untracked files present'
- fi
-@@ -42,6 +41,10 @@
+-if u="$(git ls-files --exclude-standard --others)" && ! test -z "$u"; then
+-	die 'untracked files present'
+-fi
+-
+ echo 'Cleaning worktree'
+ if ! git clean -dfX; then
+ 	die '`git clean -dfX` failed'
+@@ -42,6 +37,10 @@
  	die '`git tag -s` failed'
  fi
  
@@ -31,7 +35,7 @@
  # We put these in a temporary directory so the first archive isn't included in the second, etc.
  echo 'Creating temporary directory'
  TMPDIR=$(mktemp -d)
-@@ -94,7 +97,4 @@
+@@ -94,7 +93,4 @@
  echo 'Cleaning up'
  rmdir $TMPDIR
  
